FROM golang:1.26.0-trixie AS builder
WORKDIR /app
COPY . .
RUN go build -o main main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go

FROM alpine:latest 
WORKDIR /app
COPY --from=builder app/main .
COPY app.env .

EXPOSE 8080
CMD [ "/app/main" ]

while docker run it gives 
exec /app/main: no such file or directory
fix - RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main main.go. (as shown above)